import pandas as pd
import numpy as np
import joblib
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import os
import uvicorn
from statsmodels.tsa.stattools import acf

app = FastAPI(title="M5 Forecasting API")

# --- 1. MIDDLEWARE (CORS) ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 2. CONFIGURATION & PATHS ---
# These paths are relative to the project root (/app)
DATA_DIR = "backend/data"
PROCESSED_DATA_PATH = f"{DATA_DIR}/processed/m5_improved.parquet"
LEADERBOARD_PATH = f"{DATA_DIR}/item_leaderboard.csv"
MODEL_DIR = "models"

MODELS = {}

# 1. Update the Quantile list to match your actual files
QUANTILES = [0.005, 0.025, 0.165, 0.25, 0.5, 0.75, 0.835, 0.975, 0.995]

# 2. Update the Pathing logic
# Use absolute-style paths relative to the /app workdir
MODEL_DIR = "models/model_alpha" 
DATA_DIR = "backend/data" # Based on your file tree

@app.on_event("startup")
def load_assets():
    print(f"🚀 Loading Alpha Models from {MODEL_DIR}...")
    models_loaded = 0
    
    for q in QUANTILES:
        # Matches your filename pattern: model_alpha_0.5.txt
        path = f"{MODEL_DIR}/model_alpha_{q}.txt"
        
        if os.path.exists(path):
            try:
                # IMPORTANT: LightGBM .txt files are loaded differently than .pkl
                import lightgbm as lgb
                MODELS[q] = lgb.Booster(model_file=path)
                models_loaded += 1
                print(f"✅ Loaded: {path}")
            except Exception as e:
                print(f"❌ Error loading {path}: {e}")
        else:
            print(f"⚠️ Missing model: {path}")
            
    print(f"🏁 Startup complete. Loaded {models_loaded}/{len(QUANTILES)} models.")

# --- 4. HELPER LOGIC ---

def calculate_stocking_risk(total_demand, current_inventory):
    """Business logic for inventory alerts."""
    total_demand = float(total_demand)
    current_inv = float(current_inventory)
    
    if current_inv < (total_demand * 0.5):
        return {"level": "CRITICAL", "action": f"Restock {int(total_demand - current_inv) + 10} units immediately."}
    elif current_inv < total_demand:
        return {"level": "Warning", "action": "Stock is low - replenishment recommended."}
    elif current_inv > (total_demand * 2.5):
        return {"level": "Overstock", "action": "Excess inventory - pause orders."}
    
    return {"level": "Healthy", "action": "Inventory levels aligned with 28-day demand."}

def get_history(item_id, count=56):
    """Reads history from the Parquet file generated by the pipeline."""
    if not os.path.exists(PROCESSED_DATA_PATH):
        print(f"❌ Data file missing: {PROCESSED_DATA_PATH}")
        return [0.0] * count
    
    try:
        # We use Polars for fast reading if available, otherwise pandas
        df = pd.read_parquet(PROCESSED_DATA_PATH)
        # Filter for the specific item
        item_data = df[df['item_id'] == item_id].sort_values('d')
        if item_data.empty:
            return [0.0] * count
        
        return item_data['sales'].tail(count).tolist()
    except Exception as e:
        print(f"❌ Error reading history: {e}")
        return [0.0] * count

# --- 5. ENDPOINTS ---

@app.get("/")
def root():
    """Health check for Railway."""
    return {
        "status": "online",
        "models_loaded": len(MODELS.keys()),
        "data_path": PROCESSED_DATA_PATH,
        "data_exists": os.path.exists(PROCESSED_DATA_PATH)
    }

@app.get("/leaderboard")
def get_leaderboard():
    """Returns the list of items for the Streamlit sidebar."""
    if os.path.exists(LEADERBOARD_PATH):
        try:
            df = pd.read_csv(LEADERBOARD_PATH)
            df['product_name'] = df['product_name'].fillna(df['item_id'])
            return df.to_dict(orient="records")
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Error reading leaderboard: {e}")
    
    raise HTTPException(status_code=404, detail=f"Leaderboard file missing at {LEADERBOARD_PATH}")

@app.get("/predict/{item_id}")
def predict(item_id: str, current_stock: float = 0.0):
    """Main forecasting logic."""
    if not MODELS:
        raise HTTPException(status_code=503, detail="Models are not loaded on server.")

    full_h = get_history(item_id, 56)
    
    # 1. Backtest Loop (Last 28 days)
    bt_seed = np.array(full_h[:28]).copy()
    bt_preds = {str(q): [] for q in QUANTILES}
    
    # 2. Future Loop (Next 28 days)
    # Note: Simplified for production; usually requires feature matching
    # This logic assumes your model expects the last 28 days of sales as input
    try:
        # Backtest
        seed = bt_seed.copy()
        for _ in range(28):
            x = seed[-28:].reshape(1, -1)
            for q in QUANTILES:
                p = max(0.0, float(MODELS[q].predict(x)[0]))
                bt_preds[str(q)].append(p)
            seed = np.append(seed, bt_preds['0.5'][-1])

        # Forecast
        f_seed = np.array(full_h[-28:]).copy()
        f_preds = {str(q): [] for q in QUANTILES}
        seed = f_seed.copy()
        for _ in range(28):
            x = seed[-28:].reshape(1, -1)
            for q in QUANTILES:
                p = max(0.0, float(MODELS[q].predict(x)[0]))
                f_preds[str(q)].append(p)
            seed = np.append(seed, f_preds['0.5'][-1])
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference Error: {e}")

    # 3. Stats & Risk Calculation
    actuals = np.array(full_h[-28:])
    losses = []
    for q in QUANTILES:
        err = actuals - np.array(bt_preds[str(q)])
        losses.append(np.mean(np.where(err >= 0, q * err, (q-1) * err)))
    
    cv = np.std(actuals) / np.mean(actuals) if np.mean(actuals) > 0 else 0
    within = sum(1 for i in range(28) if bt_preds['0.025'][i] <= actuals[i] <= bt_preds['0.975'][i])

    # --- GET PRODUCT NAME ---
    product_name = item_id
    if os.path.exists(LEADERBOARD_PATH):
        df_map = pd.read_csv(LEADERBOARD_PATH)
        name_row = df_map[df_map['item_id'] == item_id]
        if not name_row.empty:
            product_name = name_row['product_name'].iloc[0]

    total_expected_demand = sum(f_preds['0.5'])
    risk_info = calculate_stocking_risk(total_expected_demand, current_stock)

    return {
        "item_id": item_id,
        "product_name": product_name,
        "history": list(actuals),
        "backtest": bt_preds,
        "forecast": f_preds,
        "metrics": {
            "wspl": round(float(np.mean(losses)), 4),
            "backtest_accuracy": round((within/28)*100, 1),
            "mpiw": round(float(np.mean(np.array(f_preds['0.975']) - np.array(f_preds['0.025']))), 2),
            "cv": round(float(cv), 3),
            "zero_pct": round(float((actuals == 0).sum()/28*100), 1)
        },
        "risk_assessment": risk_info
    }

if __name__ == "__main__":
    # Get port from Railway
    port = int(os.environ.get("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)